katanomi/pkg

.codecov.yaml
.github/PULL_REQUEST_TEMPLATE/breaking-change.md
.github/PULL_REQUEST_TEMPLATE/bug-fix.md
.github/PULL_REQUEST_TEMPLATE/normal-change.md
.github/issue-template.md
.github/workflows/knative-boilerplate.yaml
.github/workflows/knative-donotsubmit.yaml
.github/workflows/knative-go-build.yaml
.github/workflows/knative-go-test.yaml
.github/workflows/knative-release-notes.yaml
.github/workflows/knative-security.yaml
.github/workflows/knative-stale.yaml
.github/workflows/knative-style.yaml
.github/workflows/nostackdriver.yaml
README.md
go.mod
test/placeholder.go
test/placeholder_test.go

Add GitHub Actions and go.mod files

feat: Add go.mod and github actions

---

apis/meta/v1alpha1/condition.go
apis/meta/v1alpha1/objectcondition_types.go
apis/validation/common_types_validation.go
apis/validation/common_types_validation_test.go
apis/validation/nameset.go
apis/validation/nameset_test.go
examples/sample-controller/main.go

- Adds optional Annotations to ObjectCondition
- Adds Duplicated names validation for resource sets
- Adds Error handling for validation web hooks 
- Adds SetConditionbyError: helps sets a condition based on an error

feat: Adds annotations to ObjectCondition

---

go.mod
go.sum
plugin/client/interface.go
plugin/client/plugin_client.go
plugin/client/plugin_client_test.go
plugin/client/plugin_options.go

- Makes options reusable
- Adds context, base url as parameter
- Adds simple unit tests for client

feat: Change plugin client to accept context and base url

---

apis/meta/v1alpha1/objectcondition_set.go
apis/meta/v1alpha1/objectcondition_set_test.go
apis/meta/v1alpha1/objectreference.go
apis/meta/v1alpha1/objectreference_test.go

- Adds GetObjectReferenceFromObject method and helper options
- Adds SetConditionType and SetSeverity to ObjectConditionSet

feat: Adds ObjectCondition when object was not found

---

examples/sample-e2e/another/another.go
testing/framework/context.go
testing/framework/framework.go
testing/framework/testcase.go
testing/kubernetes.go
testing/warning.go

- Adds DeleteResources testing method
- Adds WarnOnError testing method

feat: Adds scheme to testing framework's TestContext

---

Makefile
sharedmain/app.go

- Adds RESTClient injection method for AppBuilder
- Updates Makefile to new content

fix: Fixes sharedmain AppBuilder with nil container

---

.golangci.yaml
Makefile
client/context_test.go
examples/sample-controller/main.go
plugin/plugin.go
plugin/route/healthz.go
plugin/route/route.go
plugin/route/system.go
sharedmain/app.go

- Adds System health checks and pprof routes

fix: Webservices registration path

---

plugin/client/auth.go
plugin/route/route.go
plugin/route/route_test.go
sharedmain/app.go

* Set http header by auth type
* Fix plugin path by adding slash

feat: Set http header by auth type

---

client/manager.go
examples/sample-api/.ko.yaml
examples/sample-api/main.go
examples/sample-api/pod.yaml
examples/sample-api/readme.md
examples/sample-controller/main.go
sharedmain/app.go
sharedmain/main.go
sharedmain/webservice.go

add sample-api

---

client/context.go
client/context_test.go
client/manager.go
examples/sample-api/main.go
examples/sample-api/readme.md
sharedmain/app.go

1. add controllerruntime/pkg/client.Client into restapi
2. change dynamic client into manager filter

change dynamic client into manager filter

---

apis/meta/v1alpha1/listmeta_types.go
plugin/client/interface.go
plugin/route/artifact.go
plugin/route/options.go
plugin/route/repository.go
plugin/route/route.go

- add list repository api
- add list artifact api
- add get artifact api
- add delete artifact api
- delete artifact api

add plugin api

---

apis/meta/v1alpha1/labels.go
plugin/client/auth.go
plugin/client/meta.go
plugin/client/plugin_client.go
plugin/route/artifact.go
plugin/route/route.go
plugin/route/route_test.go
sharedmain/app.go

1. fix plugin delete method
2. reset filter func

impl harbor api

---

apis/meta/v1alpha1/labels_annotations.go
apis/meta/v1alpha1/resource_object_types.go
apis/meta/v1alpha1/webhook_types.go
go.mod
go.sum
logging/config.go
plugin/client/interface.go
plugin/client/plugin_client.go
plugin/config/config.go
plugin/route/route.go
plugin/route/route_test.go

- Interface for IntegrationClass register
- Interface for Webhook Register
- Interface for Receiving webhooks
Implements interfaces described in https://github.com/katanomi/spec/pull/13

feat: Add Webhook Plugin SDK

---

apis/meta/v1alpha1/condition.go
testing/conditions.go

- Adds PropagateCondition function to simplify lifecycle code
- Adds ConditionBuilder for unit tests

feat: Add PropagateCondition to apis/meta/v1alpha1 for lifecycle

---

testing/kubernetes.go

The original package contained too many dependencies. We only need this one function.
Reference: https://github.com/syndesisio/syndesis/blob/0bdc9737b1c70cdff2b4b53d393d894e1a63fa2f/install/operator/pkg/util/resources.go

feat: add the ability to load resources from file

---

client/context.go
errors/errorhandling.go
sharedmain/app.go

- Add cluster.Cluster to context in AppBuilder
- Fixes error handling for RESTful APIs

feat: Add Cluster to Context in AppBuilder

---

go.sum
sharedmain/app.go

fix controller can't service healthy check

fix ctrl health check svc error

---

apis/meta/v1alpha1/condition.go
apis/meta/v1alpha1/condition_test.go

- Compares two conditions and returns true if the condition changed

feat: Add IsConditionChanged in apis/meta/v1alpha1 for quick check

---

apis/meta/v1alpha1/condition.go
apis/meta/v1alpha1/condition_test.go

- Adds LastTransition check
- Adds Reason check

fix: Condition update check not considering other fields

---

client/bearer_token.go
examples/sample-controller/config/data/clusterregistry.yaml
examples/sample-controller/main.go
multicluster/clusterregistry_client.go
multicluster/clusterregistry_client_test.go
multicluster/context.go
multicluster/context_test.go
multicluster/interface.go
multicluster/testdata/clusterregistry_client.GetConfig.cluster.yaml
multicluster/types.go
sharedmain/app.go

- Adds AppBuilder defaults and injection
- Adds ClusterRegistry implementation for the interface

feat: Add MultiCluster client

---

apis/meta/v1alpha1/labels_annotations.go
apis/meta/v1alpha1/triggeredby_types.go

- Adds common labels and annotations for create/update operations
to store user data
- adds TriggeredBy annotation to store triggeredBy struct as json

feat: Add TriggeredTimestamp to TriggeredBy for convinience

---

apis/meta/v1alpha1/objectcondition_types.go
apis/meta/v1alpha1/triggeredby_types.go

fix FromTopLevelConditionObject when top level is nil

---

controllers/interface.go
controllers/lazyloader.go
examples/sample-controller/main.go
sharedmain/app.go

- Controller to watch external resources can self-check
and will be added only when depending resources are also present

feat: Add Controller Lazy Loading

---

apis/meta/v1alpha1/gitpullrequest_types.go
plugin/client/gitcontent.go
plugin/client/gitpullrequest.go
plugin/client/interface.go
plugin/route/gitpullrequest.go
plugin/route/gitpullrequest_test.go
plugin/route/gitrepofile.go
plugin/route/route.go

add handle param for git content and add pr note list

feat:add handle param for git content

---

apis/meta/v1alpha1/cloudevent.go

add cloudevent stanardized action

---

parallel/task.go
parallel/task_test.go

add parallel logic

---

plugin/client/plugin_client.go

change default http client

---

plugin/client/plugin_client.go

remove skip insecure verify

---

plugin/client/auth.go

add oauth2 data fields

---

go.mod
hash/hash.go
hash/hash_test.go

Copy from [kubernetes/pkg/util/hash](https://github.com/kubernetes/kubernetes/blob/b695d79d4f967c403a96986f1750a35eb75e75f1/pkg/util/hash/hash.go).
Avoid directly importing `k8s.io/kubernetes`.

feat: add hash function

---

apis/meta/v1alpha1/labels_annotations.go

add annotations for resource scope

---

client/manager.go

Before this fix the client.ManagerFilter would take 500ms to 3s to finish executing.
Checking init options for the client, a RESTMapper object can be provided
Using the service account's generated client RESTMapper save the time
the client needs to crawl all api resources inside the kubernetes cluster
and reducing client generation to 1~3ms

fix: Client construction very slow in ManagerFilter for RESTful APIs

---

apis/validation/name_validation.go
apis/validation/name_validation_test.go

allows more complex names for resources

feat: Add DNS1123 with underscore

---

apis/meta/v1alpha1/listmeta_types.go
plugin/client/meta.go
plugin/client/plugin_options.go
plugin/route/options.go

Adds headers and methods to provide sub resources data to plugins

fix: Add Subresources data as header for plugins

---

apis/meta/v1alpha1/auth_types.go
plugin/client/plugin_options_test.go
plugin/client/testdata/secret.yaml

we need the accesstonkenkey make sure we can clone
the git repository
accesstokenkey will be used as username while
accesstoken will be used as password

add accesstokenkey to authTokenstatus

---

plugin/route/gitbranch.go
plugin/route/gitbranch_test.go
plugin/route/gitcommit.go
plugin/route/gitcommit_test.go
plugin/route/gitcommitcomment.go
plugin/route/gitcommitstatus.go
plugin/route/gitpullrequest.go
plugin/route/gitpullrequest_test.go
plugin/route/gitrepofile.go
plugin/route/gitrepository.go

cherry-pick https://github.com/katanomi/pkg/pull/147

change git repository route

---

apis/meta/v1alpha1/labels_annotations.go

* feat: add annotation key for artifact alias
* https://github.com/katanomi/spec/pull/81

feat: add annotation key for artifact alias

---

.github/workflows/knative-boilerplate.yaml
.github/workflows/knative-go-build.yaml
.github/workflows/knative-go-test.yaml
.github/workflows/knative-release-notes.yaml
.github/workflows/knative-style.yaml
.github/workflows/nostackdriver.yaml
Makefile
examples/sample-e2e/another/another.go
examples/sample-e2e/e2e_test.go
examples/sample-e2e/testcase_test.go
go.mod

upgrade golang version from 1.16 to 1.17

upgrade go version

---

restclient/statuscode.go

fix: GetErrorFromResponse hand non-null err parameters

fix: check err param, and point nil.

---

system/env.go

feat: add get ClusterName from env.

---

sharedmain/app.go

set plugin attribtes from yaml

plugin attributes from yaml

---

apis/meta/v1alpha1/image_config_types.go
go.mod
go.sum
plugin/client/interface.go
plugin/route/artifact.go
plugin/route/route.go

add image config api

---

plugin/route/route.go

The query key in the URL when defining a repository search.

imp: define repository search key.

---

apis/meta/v1alpha1/labels_annotations.go

add image registry endpoint annotation
- X ] Release notes block below has been filled in or deleted (only if no user facing changes)

add image endpoint

---

apis/meta/v1alpha1/project_manage_issue_types.go

fix project relatedIssue json tag.

fix: relateIssue json tag.

---

apis/meta/v1alpha1/project_funcs.go
apis/meta/v1alpha1/project_funcs_test.go

add project list funcs：
* paginate
* sort
* filter

add project list funcs

---

sharedmain/app.go

fix middleware duplicate registration problem
two registered places：
- [		ws, err := route.NewService(plugin, a.filters...)](https://github.com/katanomi/pkg/blob/52a46bff12dec2a0797a54e8a039df13297dcc4a/sharedmain/app.go#L439)
- [				a.container.Filter(filter)](https://github.com/katanomi/pkg/blob/52a46bff12dec2a0797a54e8a039df13297dcc4a/sharedmain/app.go#L516)

fix middleware duplicate registration problem

---

common/paginate.go
common/paginate_test.go

feat: add paginate function.

---

apis/meta/v1alpha1/artifact_funcs.go
apis/meta/v1alpha1/project_funcs.go

add repository funcs

---

apis/meta/v1alpha1/project_manage_branch_types.go
apis/meta/v1alpha1/project_manage_issue_types.go

fix issue branch auth error

---

apis/meta/v1alpha1/user_types.go

fix user auth

---

client/defaults.go
plugin/client/plugin_client.go
sharedmain/app.go

reset resty client timeout

---

apis/meta/v1alpha1/labels_annotations.go

add secret apply namesapaces annotations deal with some cases that using secret across namespaces
```release-note
NONE
```

add secret apply namesapaces annotations

---

.build/build.yaml

add `build.yaml` used by katanomi CI

add build.yaml

---

pointer/pointer.go
pointer/pointer_test.go

add helper function for convert basic type

add helper function for convert basic type

---

.github/workflows/knative-style.yaml
apis/data/v1alpha1/groupversion_info.go
secret/selector.go
secret/selector_test.go
secret/sorter.go

support secret selection according https://github.com/katanomi/spec/blob/main/3.core.credential.selection.md
For pull requests with a release note:
```release-note
support secret selection according https://github.com/katanomi/spec/blob/main/3.core.credential.selection.md
```

support secret select

---

.github/workflows/knative-style.yaml
apis/meta/v1alpha1/auth_types.go
apis/meta/v1alpha1/listmeta_types.go
apis/meta/v1alpha1/listmeta_types_test.go
plugin/client/auth.go

- add dynamic define.
- add ListOption default pager.

feat: add dynamic auth type

---

multicluster/context.go

add list cluster namespace params options

fix validate crosscluster

---

apis/meta/v1alpha1/condition.go
apis/meta/v1alpha1/condition_test.go

condition 没发生变化时，不需要更新，否则会导致 ready condition 的 lastTransitionTime 发生变化，频繁触发 reconcile。

check condition before change

---

go.mod
go.sum
sharedmain/app.go

Used to change the default behavior in controller-runtime.
Ref: https://github.com/katanomi/controller-runtime/pull/1
Cherry-pick: https://github.com/katanomi/pkg/pull/203
* support custom resource lock

feat: support custom resource lock

---

apis/meta/v1alpha1/project_types.go
apis/meta/v1alpha1/project_types_test.go

feat: add project attribute.

---

apis/meta/v1alpha1/code_quality_types.go
apis/meta/v1alpha1/code_quality_types_test.go
apis/meta/v1alpha1/gitbranch_types.go
apis/meta/v1alpha1/gitbranch_types_test.go
apis/meta/v1alpha1/gitcommit_types.go
apis/meta/v1alpha1/gitcommit_types_test.go

add git resource attribute

---

apis/meta/v1alpha1/createmeta_types.go
apis/meta/v1alpha1/labels_annotations.go
plugin/client/gitpullrequest.go
plugin/client/interface.go
plugin/client/plugin_client.go
plugin/route/gitpullrequest.go
plugin/route/gitpullrequest_test.go
plugin/route/route.go

PR link: https://github.com/katanomi/spec/pull/138
- Add GitPullRequestCommentUpdater for updating PR comment

feat: update pr comment

---

parallel/page.go
parallel/page_test.go
parallel/task.go
parallel/task_test.go

chore: fix result order

---

apis/meta/v1alpha1/condition.go
apis/meta/v1alpha1/gitcommitstatus_types.go
apis/meta/v1alpha1/labels_annotations.go

feat: add constants for versioning

feat: add constants for versioning

---

testing/framework/eventually.go

chore: fix test function ResourceTopConditionIsReadyEventually

---

plugin/client/client_suite_test.go
plugin/client/context.go
plugin/client/context_test.go
plugin/client/git_plugin_client.go
plugin/client/git_plugin_client_test.go
plugin/client/plugin_client.go

* refactor: add GitPluginClient

refactor: add GitPluginClient

---

apis/meta/v1alpha1/buildmetadata_funcs.go
apis/meta/v1alpha1/buildmetadata_funcs_test.go
apis/meta/v1alpha1/testdata/gitstatus.golden.yaml
apis/meta/v1alpha1/v1alpha1_suite_test.go
substitution/merge_map.go
substitution/merge_map_test.go
substitution/substitution.go
substitution/substitution_suite_test.go
substitution/substitution_test.go

* feat: add substitution
* feat: add `GetValWithKey`

feat: add substitution

---

apis/validation/name_validation.go
apis/validation/name_validation_test.go
apis/validation/nameset_test.go

support chinese resource name

---

testing/framework/client.go
testing/framework/client_test.go

chore: add some helper function for testing api of the plugin

---

patchstatus/patch_and_record.go

* chore: adjust the error log level

chore: adjust the error log level

---

apis/meta/v1alpha1/artifact.go

ArtifactParameterType to ArtifactType

feat: add artifact common parameter type.

---

apis/meta/v1alpha1/labels_annotations.go

- feat: Add ui descriptors annotation key
- https://github.com/katanomi/spec/pull/162  

feat: Add ui descriptors annotation key

---

.gitignore
apis/meta/v1alpha1/approve_funcs.go
apis/meta/v1alpha1/approve_types.go
approval/admission_transform.go
approval/admission_transform_test.go
approval/admission_validate.go
approval/admission_validate_test.go
approval/approval_suite_test.go
approval/check_approval_result.go
approval/check_approval_result_test.go
approval/doc.go

* `WithApprovalOperator` used to approval operator
* `ValidateApproval` used to validate approval
* `CheckApprovalResults` used to check approval results
* feat: add approval package

feat: add approval package

---

apis/meta/v1alpha1/buildmetadata_types.go
apis/meta/v1alpha1/git_branch_funcs.go
apis/meta/v1alpha1/git_branch_funcs_test.go
apis/meta/v1alpha1/labels_annotations.go
apis/meta/v1alpha1/testdata/git_branch_funcs_getbranchstatus.full.golden.yaml
apis/meta/v1alpha1/testdata/git_branch_funcs_getbranchstatus.full.yaml
apis/meta/v1alpha1/testdata/git_branch_funcs_getbranchstatus.weburl.yaml

feat: add git branch methods WIP

feat: add git branch methods

---

apis/meta/v1alpha1/approve_types.go

* chore: approved remove omitempty

chore: approved remove omitempty

---

apis/meta/v1alpha1/labels_annotations.go

add resourceScope.autoGenerate annotation.

feat: add resourceScope.autoGenerate annotation.

---

apis/data/v1alpha1/zz_generated.deepcopy.go
apis/meta/v1alpha1/constant.go
apis/meta/v1alpha1/testcaseexecution_types.go
apis/meta/v1alpha1/testcaseexecution_types_test.go
apis/meta/v1alpha1/testplan_types.go
apis/meta/v1alpha1/zz_generated.deepcopy.go

refactor: test management optimization

---

apis/artifacts/v1alpha1/artifact_version.go
apis/artifacts/v1alpha1/artifact_version_test.go
apis/artifacts/v1alpha1/testdata/ArtifactVersion.GetContainerImageFromValues.golden.yaml
secret/selector.go
secret/selector_test.go

modify secret select by createTime.

feat: select secret by create time.

---

apis/meta/v1alpha1/artifact_filter.go
apis/meta/v1alpha1/artifact_filter_validation.go
apis/meta/v1alpha1/artifact_filter_validation_test.go
apis/meta/v1alpha1/artifact_validate.go
apis/meta/v1alpha1/artifact_validation_test.go

artifact filter validation

---

webhook/admission/validator_test.go

fix test fail

---

apis/meta/v1alpha1/artifact_filter.go
apis/meta/v1alpha1/artifact_filter_validation.go
apis/meta/v1alpha1/artifact_filter_validation_test.go
apis/meta/v1alpha1/artifact_validate.go
apis/meta/v1alpha1/artifact_validation_test.go

add artifact filter validation

add artifact filter validation

---

apis/meta/v1alpha1/artifact_filter_validation.go
apis/meta/v1alpha1/artifact_filter_validation_test.go

fix env filter

---

client/manager.go
errors/errorhandling.go

chore: fix the format of api error response

---

apis/meta/v1alpha1/buildmetadata_funcs.go
apis/meta/v1alpha1/buildmetadata_funcs_test.go
apis/meta/v1alpha1/buildmetadata_types.go
apis/meta/v1alpha1/testdata/gitstatus.golden.yaml
config/config_suite_test.go
config/manager.go
config/manager_test.go

* refactor: add lock for config
* feat: add version for git status
- https://github.com/katanomi/spec/pull/180

refactor: add lock for config

---

apis/meta/v1alpha1/gitbase_types.go
apis/meta/v1alpha1/listmeta_types.go
parallel/fetch.go
parallel/fetch_test.go
plugin/route/options.go

feat: add helper function to fetching all data

---

apis/meta/v1alpha1/listmeta_types.go
apis/meta/v1alpha1/listmeta_types_test.go

chore: add helper function for `ListOption`

---

command/logger/block.go
command/logger/block_test.go
command/logger/print.go
command/logger/print_test.go
command/options/command.go
command/options/path.go
command/options/quality_gate.go
command/options/quality_gate_rules.go
command/options/register.go
command/options/register_test.go
command/options/report.go
command/options/scan_flags.go
command/options/suite_test.go
command/options/tool_image.go
command/qualitygate/doc.go
command/qualitygate/error.go
command/validators/doc.go
command/validators/metrics.go
command/validators/metrics_test.go
command/validators/suite_test.go

feat: add useful functions for cli

---

apis/meta/v1alpha1/gitbase_types.go
apis/meta/v1alpha1/listmeta_types.go
apis/meta/v1alpha1/listmeta_types_test.go
parallel/fetch.go
parallel/fetch_test.go
plugin/route/options.go

cherry pick from :
- https://github.com/katanomi/pkg/pull/289
- https://github.com/katanomi/pkg/pull/298

cherry pick pr 289 298

---

apis/meta/v1alpha1/buildmetadata_funcs.go
apis/meta/v1alpha1/buildmetadata_funcs_test.go
apis/meta/v1alpha1/buildmetadata_types.go
apis/meta/v1alpha1/resource_object_types.go
apis/meta/v1alpha1/resource_object_types_test.go
apis/meta/v1alpha1/testdata/gitstatus.golden.yaml
apis/meta/v1alpha1/testdata/resource_url.valid.yaml
apis/validation/addressable_validation_test.go
config/config_suite_test.go
config/manager.go
config/manager_test.go
secret/get_secret.go
secret/get_secret_test.go
secret/selector.go

git cherry-pick 8078a700b3a0914dff6c664d7443a2e3b8e9e6b2
git cherry-pick d81664fd347c01d0232e376d939bfcbe5d82bd39

chore: sync from main

---

apis/meta/v1alpha1/labels_annotations.go

feat: add secret sync label.

---

command/options/code_linter.go
command/options/code_linter_test.go
command/options/command.go
command/options/command_test.go
command/options/context.go
command/options/context_test.go
command/options/dependency_repos.go
command/options/register_test.go
command/options/tool_image.go
command/validators/url.go
command/validators/url_test.go

chore: add some command options

---

apis/codequality/v1alpha1/testdata/UnitTestsResult.GetObjectWithValues.fullWithError.golden.yaml
apis/codequality/v1alpha1/unit_tests.go
apis/codequality/v1alpha1/unit_tests_funcs.go
apis/codequality/v1alpha1/unit_tests_funcs_test.go

feat: add fields of automated test for reusing unit test

---

secret/selector.go
secret/selector_test.go

add select secret by annotation.

feat: select secret by annotation.

---

apis/meta/v1alpha1/tool_service.go
encoding/jsonpath_node.go
plugin/client/error.go
plugin/client/interface.go
plugin/client/plugin_client.go
plugin/client/tool_service.go
plugin/client/tool_service_test.go
plugin/config/env.go
plugin/plugin_base.go
plugin/plugin_base_test.go
plugin/route/route.go
plugin/route/tool.go
plugin/route/tool_test.go

chore: add liveness and initialize interface for plugin

---

secret/selector.go
secret/selector_test.go

feat: select secret by annotation(0.5).

---

artifacts/uri.go
artifacts/uri_test.go
command/options/container_images.go
command/options/container_images_test.go
command/options/oci_container_image_build_url.go
go.mod
go.sum

feat: add image option(0.5).

---

artifacts/uri.go
artifacts/uri_test.go
command/options/container_images.go
command/options/container_images_test.go
command/options/oci_container_image_build_url.go
go.mod
go.sum

feat: add image option.

---

config/manager.go
testing/config_manager.go
testing/config_manager_test.go

Add NewTestConfig for testing.
It will return the data you input to mock the data you need.

Add test config manager

---

apis/meta/v1alpha1/testcaseexecution_types.go
apis/meta/v1alpha1/testcaseexecution_types_test.go

fix: allow space between name chars

---

registry/detect_scheme.go
registry/helper.go
registry/helper_test.go

* chore: optimize logs
* refactor: add ctx paramter to interface RegistryPinger

chore: optimize logs

---

apis/meta/v1alpha1/project_manage_branch_funcs.go
apis/meta/v1alpha1/project_manage_branch_funcs_test.go

add project manage branch spec equal.

feat: add project manage branch equal.

---

apis/meta/v1alpha1/project_manage_branch_funcs.go
apis/meta/v1alpha1/project_manage_branch_funcs_test.go

add project manage branch equal. 
cherry-pick from: #345 

feat: add project manage branch equal. 

---

apis/meta/v1alpha1/project_manage_branch_funcs.go
apis/meta/v1alpha1/project_manage_branch_funcs_test.go

add project manage branch equal.
cherry-pick from: https://github.com/katanomi/pkg/pull/345

feat: add project manage branch equal. (#345)

---

apis/meta/v1alpha1/project_types.go

Add ProjectSubType types such as nexus maven, raw, go, python, npm, etc.

feat: nexus increases projectsubtype type.

---

apis/meta/v1alpha1/labels_annotations_funcs.go
apis/meta/v1alpha1/labels_annotations_funcs_test.go
patchstatus/patch_and_record.go

feat: add function to detect if key exist

---

manager/interface.go
sharedmain/app.go

fix: avoid assert failed

---

apis/meta/v1alpha1/buildmetadata_funcs.go
apis/meta/v1alpha1/buildmetadata_funcs_test.go

fix: avoid panic

---

apis/meta/v1alpha1/labels_annotations_funcs.go
apis/meta/v1alpha1/labels_annotations_funcs_test.go

chore: add map filter function

---

plugin/storage/capabilities_test.go

fix: test case asserting slice result out of order

---

plugin/client/interface.go
plugin/storage/interface.go

- change name of dependent resource interface

fix: change name of dependent resource interface

---

apis/selection/v1alpha1/base_filter.go
apis/selection/v1alpha1/base_filter_test.go
apis/selection/v1alpha1/testdata/baseFilter.configmap.yaml
finalizer/finalizer.go
finalizer/finalizer_test.go
finalizer/suite_test.go
finalizer/testdata/configmap.withFinalizer.yaml
finalizer/testdata/configmap.withOtherFinalizer.yaml
finalizer/testdata/configmap.yaml

feat: add helper functions to manager finalizer

---

webhook/admission/defaulter.go
webhook/admission/defaulter_test.go
webhook/admission/inject.go
webhook/admission/register.go
webhook/admission/validator.go
webhook/admission/validator_test.go

feat: admission webhook support inject context

---

apis/meta/v1alpha1/gitrepofile_types.go

corresponds to the sha returned by the tree list.
This sha is not a commit id.
- https://github.com/katanomi/spec/pull/219

feat: add node sha for git repo file

---

errors/temporary_error.go
errors/temporary_error_test.go

fix: Add BadRequest as a non-temporary error in error check

---

multicluster/clusterregistry_client.go
testing/framework/context.go
testing/framework/testcase.go

add list cluster namespace implemention for MultiClusterClient
```release-note
NONE
```

add list cluster namespace implemention for MultiClusterClient

---

apis/applications/v1alpha1/deploy_application_status_funcs.go
apis/applications/v1alpha1/deploy_application_status_funcs_test.go

fix: DeployApp results with empty attributes

---

tekton/labels_annotations.go
tekton/pipelinerun_meta.go
tekton/pipelinerun_meta_test.go
tekton/testdata/PipelineRun.Normal.yaml
tekton/testdata/PipelineRun.ownerBuildRun.golden.yaml
tekton/testdata/PipelineRun.ownerDeliveryRun.golden.yaml
tekton/testdata/PipelineRunMeta.buildRun.yaml
tekton/testdata/PipelineRunMeta.deliveryRun.yaml

- add fucns to inject piplinerun owener references as meta.json

feat: add funcs to inject pipelinerun meta

---

apis/variable/marshal.go
multicluster/clusterregistry_client.go
multicluster/context.go
multicluster/context_test.go
multicluster/interface.go

Some scenarios rely on the list interface to determine permissions, while others just need to get the namespaces that can be accessed.

feat: add ignore forbidden flag for multicluster

---

plugin/client/git_plugin_client.go
secret/get_secret.go

chore: adjust log

---

apis/archive/v1alpha1/condition_funcs.go
apis/archive/v1alpha1/condition_funcs_test.go
apis/archive/v1alpha1/query.go
apis/archive/v1alpha1/record_funcs.go
apis/archive/v1alpha1/record_funcs_test.go
apis/archive/v1alpha1/testdata/condition.completedStatus.golden.yaml
apis/meta/v1alpha1/data_map.go
apis/meta/v1alpha1/data_map_test.go
apis/meta/v1alpha1/historylimits_types.go
apis/meta/v1alpha1/historylimits_types_test.go
apis/variable/marshal.go
go.mod
go.sum

fix: fix some issues

---

client/rbac_filter.go
client/rbac_filter_test.go

feat: add subject review filter for dynamic resource

---

client/impersonate_filter.go

fix dynamic client will not append imperonsate config
```release-note
NONE
```

fix impersonated dynamic client

---

plugin/client/plugin_client.go
plugin/client/plugin_client_test.go

fix: clone not effective

---

secret/resource_path.go
secret/resource_path_test.go
secret/selector.go

chore: add helper function to manage resource scope

---

multicluster/clusterregistry_client.go
multicluster/clusterregistry_client_test.go
multicluster/interface.go
testing/mock/github.com/katanomi/pkg/multicluster/interface.go

chore: add `ListClustersNamespaces` for multicluster Interface

---

testing/mock/github.com/katanomi/pkg/multicluster/interface.go

chore: generate mock code for multi-cluster interface

---

apis/archive/v1alpha1/record.go
apis/storage/v1alpha1/fileobject.go
client/rbac_filter.go
plugin/route/route.go
plugin/storage/interface.go
plugin/storage/route/archive/v1alpha1/archive.go
plugin/storage/route/core/v1alpha1/auth.go
plugin/storage/route/filestore/v1alpha1/filemeta.go
plugin/storage/route/filestore/v1alpha1/fileobject.go
plugin/storage/route/route.go
sharedmain/app.go

add permissions check for storage api
```release-note
NONE
```

add permission for feature storage

---

apis/archive/v1alpha1/field.go

chore: fix the topNamespace filed name

---

storage/cleanup/cleanup_suite_test.go
storage/cleanup/pvc.go
storage/cleanup/pvc_test.go
storage/testdata/cleanup/cache-pvc.yaml
storage/testdata/cleanup/pipelinerun.yaml
storage/testdata/cleanup/pvc.yaml
storage/testdata/cleanup/taskrun.yaml

add public function: cleanup taskrun pvc

add public func cleanup pvc

---

client/client_suite_test.go
client/context.go
client/options.go
client/options_test.go

feat: add get options

---

storage/cleanup/pvc.go
storage/cleanup/pvc_test.go

fix clean pvc not found

---

storage/cleanup/pvc.go
storage/cleanup/pvc_test.go

check pvc was created by manual

check pvc manual

---

plugin/storage/capabilities/capabilities_test.go
plugin/storage/capabilities/filestore/v1alpha1/interface.go
plugin/storage/client/versioned/filestore/v1alpha1/fileobject.go
plugin/storage/client/versioned/filestore/v1alpha1/fileobject_test.go
plugin/storage/route/route_suite_test.go

add funcs to inject & extract FileObjectClient with context for the convenience of unit test. 

feat: add funcs to inject & extract FileObjectClient for unit test

---

webhook/admission/approval_validate.go
webhook/admission/approval_validate_test.go

fix: avoid building data to bypass the approval policy

---

config/feature_flags.go

Add merge request status check timeout 10m

Add default merge request status check timeout

---

manager/interface.go

add resource lock interface
```release-note
NONE
```

add resource lock interface

---

sharedmain/app.go

remove ResourceLockFunc in app and change it to manager.ResourceLockFunc
```release-note
NONE
```

remove ResourceLockFunc in app and change it to manager.ResourceLockFunc

---

maps/merge.go
maps/merge_test.go
maps/sorted.go
maps/sorted_test.go

Co-authored-by: fm <mingfu@alauda.cn>
Pick maps package dir files from main as lib funcs.

chore: pick map package from main

---

go.mod
go.sum
hash/hash.go
hash/hash_test.go

ignore file filter

---

registry/manifests.go
registry/manifests_test.go

support insecure tls

---

apis/artifacts/v1alpha1/upload.go

add fileupload ResourceAttribute.

feat: add fileupload ResourceAttribute.

---

catalog-info.yaml

[auto-commit] create catalog-info.yaml

[auto-commit] create catalog-info.yaml

---

errors/convert_plugin_response_error.go
errors/convert_response_error.go
errors/errorhandling.go
errors/errorhandling_test.go
errors/status_reason_error.go

For example FileNotFound GitRevisionNotFound etc.

Define some special error for k8s status error

---

apis/archive/v1alpha1/record.go

chore: add ID field for archive record

---

apis/archive/v1alpha1/field.go
apis/archive/v1alpha1/record.go
apis/meta/v1alpha1/cursor.go

Fix/archive performance 0.7

---

plugin/client/gitpullrequest.go

fix list pr with commit error

---

apis/meta/v1alpha1/project_types.go
sharedmain/app.go

Add readonly and limited fields for project

Add readonly and limited fields for project

---

apis/meta/v1alpha1/project_types.go
apis/storage/v1alpha1/labels_annotations.go

fix sonar scan Security Hotspots
```release-note
NONE
```

fix sonar scan Security Hotspots

---

client/defaults.go
client/defaults_test.go

added HttpClientOptionFunc for NewHTTPClient method

---

maps/equal.go

chore: fix code style issue

---

plugin/route/gitcommit.go

chore: remove debug log

---

secret/selector.go

make SelectToolSecretFrom method public

---

apis/meta/v1alpha1/cloudevent.go
apis/meta/v1alpha1/labels_annotations.go

add new const represent pullrequest title

add new const represent pullrequest title

---

apis/archive/v1alpha1/field.go
apis/archive/v1alpha1/query.go
apis/archive/v1alpha1/record.go

fix: add topOwner fields

---

apis/meta/v1alpha1/repository_types.go

feat: add FileDiectorySubType

---

url/project_key.go
url/project_key_test.go

chore: move url2projectkey to pkg

---

apis/meta/v1alpha1/project_funcs.go
apis/meta/v1alpha1/project_funcs_test.go

move FilterProject from integrations to pkg

feat: move FilterProject to pkg

---

apis/artifacts/v1alpha1/artifact_properties.go
apis/artifacts/v1alpha1/upload.go
apis/meta/v1alpha1/artifact_types.go
apis/meta/v1alpha1/listmeta_types.go
apis/meta/v1alpha1/listmeta_types_test.go
plugin/client/interface.go
plugin/client/plugin_client.go
plugin/client/plugin_options.go
plugin/client/projectartifact.go
plugin/client/projectartifact_test.go
plugin/route/artifact.go
plugin/route/artifact_test.go
plugin/route/route.go

1. add structs for binary artifact properties
2. make subResources option being able to used without listOption
3. add project-level artifact interfaces
4. add project artifact http routes

feat: binary artifact display

---

plugin/route/artifact_test.go
plugin/route/route.go
plugin/route/route_test.go

fix: integration attributes methods

---

multicluster/clustersmanager.go
multicluster/clustersmanager_test.go
multicluster/filter_test.go
multicluster/interface.go
multicluster/multicluster_suite_test.go
multicluster/testdata/clusterreferences.init.yaml
parallel/task.go
secret/mutate_test.go

* add filters to allow condition checking

feat: multiple clusters filter

---

.build/downstream-test.yaml
apis/archive/v1alpha1/condition_funcs.go
apis/archive/v1alpha1/condition_funcs_test.go
apis/archive/v1alpha1/query.go
apis/archive/v1alpha1/query_test.go
apis/archive/v1alpha1/testdata/condition.eq.column.golden.yaml
go.mod
go.sum

feat: add equal column condition

---

registry/image.go
registry/image_test.go

fix: push http registry image.

---

errors/status_reason_error.go
storage/storageclass/storageclass.go
tekton/pipelinerun_funcs.go
tekton/pipelinerun_funcs_test.go
tekton/testdata/PipelineRun.workspaces.withPVCName.yaml
tekton/testdata/PipelineRun.workspaces.yaml
tekton/testdata/scList.withDefault.yaml
tekton/testdata/taskrunList.pipelineRunLabel.all.yaml
tekton/testdata/taskrunList.pipelineRunLabel.onlyTemplateWorkspaces.yaml
tekton/testdata/taskrunList.pipelineRunLabel.partialTemplateWorkspaces.yaml
tekton/testdata/workspaces.full.golden.yaml
tekton/testdata/workspaces.noCachePVC.golden.yaml
tekton/workspaces.go
tekton/workspaces_test.go

* add funcs for tekton package to get workspaces binding from pipelinerun
* add DefaultStorageClassNotFound error reason

feat: buildRun status add workspace binding

---

testing/framework/cluster/builder.go

test: set `TestNamespaceCondition` as the first condition

---

controllers/sync_reconciler.go
controllers/sync_reconciler_test.go

add schedule reconciler

---

apis/meta/v1alpha1/buildmetadata_funcs.go
apis/meta/v1alpha1/buildmetadata_funcs_test.go
apis/meta/v1alpha1/gitbase_types.go
command/root/root.go

add BaseGitStatus methods & const for git file

feat: add BaseGitStatus methods & const for git file

---

testing/loadfile.go
testing/loadfile_test.go

chore: add load file as bytes.

---

config/feature_flags.go

add pr checking timeout continue flag
- https://github.com/katanomi/spec/pull/274

fix: add pr checking timeout continue flag

---

catalog.yaml

chore: adjust catalog owner

---

plugin/route/route.go
plugin/route/route_test.go

fix: add missing methods of plugin

---

testing/framework/conformance/caseproxy.go
testing/framework/conformance/interface.go
testing/framework/conformance/node.go
testing/framework/conformance/node_test.go

feat: support to mark test case as optional

---

plugin/route/healthz.go
plugin/route/system.go

add openapi tags

---

references/onwer_references.go
references/onwer_references_test.go

Add FindOwnerReferenceWithGroupKind function for find owner with provided group and kind

---

multicluster/clusterregistry_client.go

fix ca insecure conflicts

---

testing/fake/builder.go
testing/fake/builder_test.go
testing/fake/filter.go
testing/fake/opa/policy.go

fix fake policy id

---

apis/artifacts/v1alpha1/registry_types.go
apis/artifacts/v1alpha1/registry_types_test.go

feat: add generate docker auth func.

feat: add generate docker auth func.

---

config/feature_flags.go
config/feature_flags_test.go

- https://github.com/katanomi/spec/issues/289

feat: add feature flag for clustertask

---

config/feature_flags.go
config/feature_flags_test.go

- https://github.com/katanomi/spec/pull/291

feat: add feature flag for clustertask creation and migration

---

system/env.go
system/env_test.go

feat: add base domain env key.

feat: add base domain env key.

---

testing/framework/conformance/node.go
testing/framework/conformance/node_test.go
testing/framework/conformance/testcase.go
testing/framework/conformance/testcase_test.go

feat: deepcopy custom labels of conformance test node

---

.build/downstream-test.yaml
apis/meta/v1alpha1/gitpullrequest_types.go
apis/meta/v1alpha1/gitpullrequest_types_test.go

feat: Add IsValid method for MergeStatus type

---

.build/build.yaml
.build/downstream-test.yaml
go.mod
go.sum
testing/framework/conformance/testcase.go
testing/framework/conformance/testcase_test.go

feat: add check for duplicate testcase builds.

---

testing/context/context.go
testing/context/context_test.go
testing/script/git.go
testing/script/git/create_branch.sh
testing/script/git/create_commit.sh
testing/script/git/create_multi_commit.sh
testing/script/git/create_tag.sh
testing/script/git/init_repo.sh
testing/script/script.go
testing/script/script_builder.go
testing/script/script_test.go

Move script from testing to pkg

---

apis/meta/v1alpha1/gitoption_types.go
apis/meta/v1alpha1/gitpullrequest_types.go

spec: https://github.com/katanomi/spec/pull/303/files

use pull request state enum

---

apis/artifacts/v1alpha1/uri.go
apis/artifacts/v1alpha1/uri_test.go

fix: parse uri not cover raw value.
```release-note
NONE
```

fix: parse uri not cover raw value.

---

.build/build.yaml
plugin/client/plugin_options.go
plugin/client/plugin_options_test.go
plugin/route/route.go
plugin/route/route_test.go

https://github.com/katanomi/pkg/commit/7199d5c761c08801d5fd1f2c504accc161cc4c22
https://github.com/katanomi/pkg/commit/cfb454b308a3ce7714e32ae95f7e58b79a4535cf

cherry-pick bugfix commit

---

controllers/context.go

add num requeues to context

---

command/options/vuln_scan.go
command/options/vuln_scan_metrics.go
command/options/vuln_scan_metrics_test.go

feat: add vuln scan result limit

---

workers/cronworker.go

chore: add logger for cron worker

---

config/feature_flags.go
plugin/route/route.go
sharedmain/app.go

feat: add a toggle to access the OpenAPI documentation

---

apis/archive/v1alpha1/condition_funcs.go
apis/archive/v1alpha1/field.go
apis/archive/v1alpha1/field_test.go
apis/archive/v1alpha1/params.go
apis/archive/v1alpha1/params_test.go
apis/archive/v1alpha1/query.go
apis/archive/v1alpha1/testdata/condition.completedStatus.golden.yaml

improve: support metadata search style like k8s labelsector

---

check/setup.go
go.mod
go.sum

fix: check whether Tekton is installed

---

check/setup.go
go.mod
go.sum

cherry-pick: https://github.com/katanomi/pkg/pull/595

fix: check whether Tekton is installed (#595)

---

check/setup.go
client/options.go
client/options_test.go

fix (performance): reduce installation check time consumption

---

check/setup.go
client/options.go
client/options_test.go

fix (performance): reduce installation check time consumption (#597)

---

apis/meta/v1alpha1/param_types.go
hack/patch-tekton-params.sh
hack/patches/0001-remove-unused-param-logic-based-on-tekton-definition.patch

add params json tag to fix make generate error
```release-note
NONE
```

fix to add json tags on tekton params

---

apis/meta/v1alpha1/condition.go
apis/meta/v1alpha1/condition_test.go
fieldindexer/types.go
sharedmain/app.go
sharedmain/app_test.go
webhook/admission/validator.go

1. support set condition message
2. move fieldindex packages to `package fieldindex` from sharedmain
```release-note
Breaking Change: Move `FieldIndexer` types to package `fieldindex`
```

support to set condition message and refactor fieldindex packages
