examples/sample-plugin/harbor/api.go, examples/sample-plugin/main.go, plugin/client/interface.go, plugin/route/route_test.go, sharedmain/app.go
- Add Setup for initialization setup
This is a breaking change to the current Plugin API which
demands implementation of a new method
Affects:
- https://github.com/katanomi/integrations-template
- https://github.com/katanomi/integrations-harbor
- https://github.com/katanomi/integrations-gitlab
- https://github.com/katanomi/integrations-fake
@airycanon @NigelZHANG
=> feat: Add Setup method for plugins to inject context and logger

apis/meta/v1alpha1/labels_annotations_funcs.go, apis/meta/v1alpha1/labels_annotations_funcs_test.go, multicluster/clusterregistry_client.go, namespace/context.go, namespace/context_test.go
- Removes the fmt.Println entry leaking values in MultiClientCluster
- Adds CopyLabels and CopyAnnotations quick helpers
- Adds Namespace context methods
=> fix: MultiClusterClient leaking token using println

.gitignore, client/bearer_token.go, client/manager.go, client/manager_test.go, sharedmain/app.go
When not providing a Bearer token the default implementation of Manager
will return a 401 Unauthorized error. The token contents are currently
not validated. With this change the Manager filter was removed from
AppBuilder as default filter to avoid other conflicts and needs to be
initiated manually in specific Webservices with the following snipet:
```golang
// inside Webservice Setup method
ws := &restful.WebService{}
if manager := client.ManagerCtx(ctx); manager != nil {
ws = ws.Filter(manager.Filter(ctx))
}
```
=> feat: Change the client.Manager filter to be strict require token

apis/meta/v1alpha1/triggeredby_types.go, multicluster/interface.go, testing/mock/github.com/katanomi/pkg/multicluster/interface.go, webhook/admission/context.go, webhook/admission/defaulter.go, webhook/admission/funcs.go, webhook/admission/register.go, webhook/admission/transform.go
Enables a more complex and feature rich Default method for types
to provide a context parameter in the Default function. This context
will be populated using knative/pkg/apis methods and also includes the
request object for further processing
=> feat: Add Defaulting (Mutating) webhook with transforms and context

apis/meta/v1alpha1/artifact_types.go, apis/meta/v1alpha1/gitrepositories_types.go, apis/meta/v1alpha1/repository_types.go, client/defaults.go, client/manager.go, client/manager_test.go, client/rbac_filter.go, client/rbac_filter_test.go, logging/filter.go, sharedmain/app.go
- Adds client to be initiated in Manager filter
- Move config defaults to client package
- Adds RBAC SelfSubjectReview to check permissions
=> feat: Add RBAC filter for APIs using meta.katanomi.dev

testing/kubernetes.go, testing/kubernetes_test.go, testing/testdata/loadkuberesources.yaml, testing/testing_suite_test.go
This logic can be removed after upgrading to controller-runtime v0.10.1
Ref: https://github.com/kubernetes-sigs/controller-runtime/pull/1662
=> feat: loaded resources support list of fake client

plugin/route/artifact.go, plugin/route/artifact_test.go, plugin/route/gitrepository.go, plugin/route/project.go
Unified routing parameters (project) use the format {project:*}
- [√] [`spec` PR link](https://github.com/katanomi/spec) included(API not change)
- [√] Follows the [commit message standard](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md#commits)
- [√] Meets the [contributing guidelines](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md) (including
- [√] Test cases with documentation and functionality works as expected using current and related github repos (MUST deploy and check)
- [√] Release notes block below has been filled in or deleted (only if no user facing changes)
Bug fixes
```release-note
Unified routing parameters (project) use the format {project:*}
```
=> fix:support GetGitRepository use subgroup

.github/workflows/knative-boilerplate.yaml, .github/workflows/knative-go-build.yaml, .github/workflows/knative-go-test.yaml, .github/workflows/knative-release-notes.yaml, .github/workflows/knative-style.yaml, .github/workflows/nostackdriver.yaml, apis/meta/v1alpha1/cloudevent.go, apis/meta/v1alpha1/webhook_types.go, examples/sample-e2e/another/another.go, examples/sample-e2e/e2e_test.go, examples/sample-e2e/testcase_test.go, plugin/client/interface.go
add interface GetWebhookSupport to support plugin register webhookType to integrationClass
- [√] [`spec` feat/add-webhook-support-interface](https://github.com/katanomi/spec/pull/80) included
- [√] Follows the [commit message standard](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md#commits)
- [√] Meets the [contributing guidelines](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md) (including
- [√] Test cases with documentation and functionality works as expected using current and related github repos (MUST deploy and check)
- [√] Release notes block below has been filled in or deleted (only if no user facing changes)
API changes
Any changes in behavior …
=> feat:add interface to get support webhook map

plugin/route/plugin.go, plugin/route/route.go
add route for plugin method unsupport
- API changes
For pull requests with a release note:
```release-note
add route for plugin method unsupport
```
=> feat:add function for plugin method unsupport

apis/meta/v1alpha1/gitcommitstatus_types.go
feat:set status for list commitstatus when one commit failed
API changes
```release-note
set status for list commitstatus when one commit failed
```
=> feat:set status for list commitstatus when one commit failed

apis/meta/v1alpha1/labels_annotations.go, apis/meta/v1alpha1/triggeredby_types.go, apis/meta/v1alpha1/triggeredby_types_test.go, webhook/admission/transform.go
* add annotation key`katanomi.dev/triggerName` to store the friendly name of the trigger.
* correction trigger timestamp
* if the creationTimestamp is not set, we use to the current time.
- https://github.com/katanomi/spec/pull/98
=> feat: add trigger name annotation key

logging/setup.go
延迟初始化日志库的加载。
目前只要间接导入了该包，比如会出现几个日志：
```
2022-03-18T22:48:15.019+0800	info	logging/config.go:116	Successfully created the logger.
2022-03-18T22:48:15.019+0800	info	logging/config.go:117	Logging level set to: debug
2022-03-18T22:48:15.019+0800	info	logging/config.go:79	Fetch GitHub commit ID from kodata failed	{"error": "\"KO_DATA_PATH\" does not exist or is empty"}
```
目前的`SetupLogger`函数还没有在其他地方被真的使用。理论上这个文件不存在，也不会对其他功能产生影响。
* lazy load logging setup
=> feat: lazy load logging setup

sharedmain/app.go
import sigs.k8s.io/controller-runtime/pkg/metrics to avoid invoking workqueue.SetProvider by knative-pkg@v0.0.0-20220128061436-ff5a1e531de2/controller/stats_reporter.go:95
https://github.com/katanomi/knative-pkg/blob/ff5a1e531de2b2eeb63d2e8b9c975d1ced840625/controller/stats_reporter.go#L95 will override 
[sigs.k8s.io/controller-runtime@v0.8.3/pkg/metrics/workqueue.go:99](https://github.com/kubernetes-sigs/controller-runtime/blob/v0.8.3/pkg/metrics/workqueue.go#L99)  that caused cannot report client-go metrics correctly.
we should ensure doing `init` of controller-runtime firstly 
fix the bugs that cannot report client-go metrics
For pull requests …
=> fix the bugs that cannot report client-go metrics

apis/meta/v1alpha1/listmeta_tyes_test.go, apis/meta/v1alpha1/listmeta_types.go
Add a method to get the first element of a key in Listoption.Search
- Any changes in behavior
```release-note
Add a method to get the first element of a key in Listoption.Search
```
=> feat:add func for get value in ListOptions.Search

errors/conver_resource_test.go, errors/convert_resource.go
add convert gvk to gvr function which easy to use k8s error function:
[k8s api errors](https://pkg.go.dev/k8s.io/apimachinery@v0.23.5/pkg/api/errors)
=> convert gvk to gvr

secret/selector.go, secret/selector_test.go
We used to only select secret with option ExcludedSecretTypes which
can help exclude secret which type in the ExcludedSecretTypes list.
Now I add SecretTypes means we only want secret which type in the
SecretTypes list.
It this option provided we will use it if not provided means there
is no limit for secret type when selecting
Signed-off-by: yuzhipeng <yuzp1996@qq.com>
=> Add SecretType to allow secret selecting with type

go.mod, go.sum, sharedmain/app.go
Used to change the default behavior in controller-runtime.
Ref: https://github.com/katanomi/controller-runtime/pull/1
* support custom resource lock
=> feat: support custom resource lock

tracing/transport.go, tracing/transport_test.go
When wrapping transport multiple times, it only takes effect once
=> wrapping transport once

parallel/task.go, parallel/task_test.go, webhook/admission/validator_test.go
=> fix task result order

apis/meta/v1alpha1/buildmetadata_funcs.go, apis/meta/v1alpha1/buildmetadata_funcs_test.go, apis/meta/v1alpha1/constant.go, apis/meta/v1alpha1/testdata/gitbranch.golden.yaml, apis/meta/v1alpha1/testdata/gitbranch.status.yaml, apis/meta/v1alpha1/testdata/gitcommit.golden.yaml, apis/meta/v1alpha1/testdata/gitcommit.status.yaml, apis/meta/v1alpha1/testdata/gitpullrequest.golden.yaml, apis/meta/v1alpha1/testdata/gitpullrequest.status.yaml, apis/validation/regexp_validation.go, apis/validation/regexp_validation_test.go
* add function to validate regular expression
* add functions to convert git status
=> feat: add functions for version request

testing/conditions.go, testing/framework/eventually.go
Integration tests checking if an object's top condition is ready
In most test cases one of the most common tasks is create a resource
and wait for it to be ready before moving on with the needed test logic
this function makes it an out-of-the-box check with custom additional checks
=> feat: Add ResourceTopConditionIsReadyEventually function to help

command/args/key_value_test.go, command/options/doc.go, command/options/log.go, command/root/doc.go, command/root/root.go, command/root/root_suite_test.go, pointer/pointer.go, pointer/pointer_test.go
other CLI programs
The base root command is simple and can be reused by multiple projects
without having to implement again and again
feat: add root command into command/root to be reusable by other CLI programs
The base root command is simple and can be reused by multiple projects
without having to implement again and again
=> feat: add root command into command/root to be reusable by

apis/meta/v1alpha1/check_funcs.go, apis/meta/v1alpha1/check_funcs_test.go
* feat: add timeout function for check approval
=> feat: add timeout function for check approval

apis/meta/v1alpha1/git_branch_funcs.go, apis/meta/v1alpha1/git_branch_funcs_test.go, apis/meta/v1alpha1/testdata/git_branch_funcs_getbranchstatus.nil.golden.yaml
- chore: Adds nil treatment for when GitBranch is nil
When generating BuildGitBranchStatus now checks and treats GitBranch as nil
and avoid panics in depending code. Some logic inside katanomi/builds was expecting
and testing for nil cases and adding this treatment here improves stability
Unit test was also added
=> chore: Adds nil treatment for when GitBranch is nil

apis/meta/v1alpha1/check_validate.go, apis/meta/v1alpha1/check_validate_test.go, webhook/admission/approval.go, webhook/admission/approval_validate.go, webhook/admission/approval_validate_test.go
In the scenario where the stagerun is created directly, the controller will initialize the check based on the stage spec information.
This is not common, but it can happen.
* fix: cannot patch stagerun
=> fix: cannot patch stagerun

secret/get_secret_test.go, secret/secret_suite_test.go, secret/selector.go, secret/selector_test.go
support to pass labels selector when select secret
```release-note
NONE
```
=> support to pass labels selector when select secret

client/defaults_test.go, sharedmain/app.go, sharedmain/sharedmain_suite_test.go, sharedmain/sharedmain_test.go
=> Add default timeout for controller-manager

client/defaults_test.go, sharedmain/app.go, sharedmain/sharedmain_suite_test.go, sharedmain/sharedmain_test.go
Previously, value of timeout can not be configured and is 10s as default value.
Now add the falg kube-api-timeout that can be configured by falg.
Signed-off-by: yuzhipeng <yuzp1996@qq.com>
Signed-off-by: yuzhipeng <yuzp1996@qq.com>
=> Add configuration for k8s client config timeout (#296)

apis/meta/v1alpha1/resource_object_types.go, apis/meta/v1alpha1/resource_object_types_test.go, apis/meta/v1alpha1/testdata/resource_url.valid.yaml, apis/validation/addressable_validation_test.go, secret/get_secret.go, secret/get_secret_test.go, secret/selector.go
* feat: resource url support automatic select secret
* fix: select secret in correct namespace
=> feat: resource url support automatic select secret

scheme/convert.go, scheme/convert_test.go
=> chore: add helper function to convert gvk to `TypeMeta`

apis/meta/v1alpha1/labels_annotations.go, apis/meta/v1alpha1/resourcepath_scene.go, plugin/client/interface.go, secret/selector.go, secret/selector_test.go
support select secret by scene
1. different http clone url used by different git tools, we should match the resource scope according http-clone url pattern. 
eg. bitbucket http clone url has a prefix of /scm, so we should match secret according such  resource url pattern
```release-note
`feature`: support select secret by scenario
```
=> support select secret by scene

testing/framework/condition.go, testing/framework/condition_test.go
* feat(test): allow rollback ignore not found
=> feat(test): allow rollback ignore not found

config/manager.go, config/manager_test.go, sharedmain/sharedmain_test.go
If cm is nil there will be a panic. So we need replace it in case trigger the panic.
=> Replace manger config ns and name with system.Namespace() and Name()

errors/errorhandling.go, errors/errorhandling_test.go, plugin/client/plugin_client.go
=> fix: fix log nil error when http request failed

command/options/oci_container_image_build.go
rename ociContainerImageBuild-url to ociContainerImageBuild
=> chore: rename ociContainerImageBuild-url

apis/artifacts/v1alpha1/registry_types.go, registry/detect_scheme_by_secret.go, registry/detect_scheme_by_secret_test.go
* feat: support anonymous detect registry scheme
=> feat: support anonymous detect registry scheme

apis/codequality/v1alpha1/unit_tests_funcs.go, apis/codequality/v1alpha1/unit_tests_funcs_test.go
- fix: zero test result
Allow IsEmpty returns false even if there is no test cases included in a test execution(failed, passed, skipped are all 0), provided that PassedTestsRate is not empty string.
Scenario:  Expect below task result could be injected into buildRun.status rather than omitted.
```
testResults:
failed: 0
passed: 0
passedTestsRate: "0.00"
skipped: 0
```
```
apiVersion: builds.katanomi.dev/v1alpha1
kind: BuildRun
metadata:
name: katanomi-adefs
namespace: default
status:
unitTestsResults:
- name: existing-result
coverage:
lines: "11"
branches: "11.33"
- name: unittest // this item will be omitted if IsEmpty returns true in this scenario.
testResults:
passed: 0
skipped: 0
failed: 0
passedTestsRate: "0.00"
```
As the author of this PR, please check off the items in this …
=> fix: zero test result

tekton/taskrun_filter_completion.go, tekton/taskrun_test.go, tekton/testdata/TaskRun.WithOwner.yaml
GetPipelineRunOwner will return pipelinerun Owner for taskrun if exist
=> Add GetPipelineRunOwner for getting piplinerun owner for taskrun

apis/meta/v1alpha1/objectcondition_types.go, apis/meta/v1alpha1/objectcondition_types_test.go, pointer/interfaces.go, pointer/interfaces_test.go
Retrun nil if input nil for FromTopLevelConditonObject or every caller have to check the input parameters.
=> Retrun nil if input nil for FromTopLevelConditonObject

testing/mock/github.com/katanomi/pkg/webhook/admission/approval.go, testing/mock/github.com/katanomi/pkg/webhook/admission/approval_with_triggeredbygetter.go, webhook/admission/transform_approval_operator.go
Transform for creating eventing will add wrong operator in some case for example automate approval.
So we skip the tranfrom for the create operation.
=> Delete transform for creating when adding approval operator

apis/meta/v1alpha1/createmeta_types.go, user/user_suite_test.go, user/userinfo.go, user/userinfo_test.go
=> chore: add helper function to get userinfo from request context

plugin/client/artifact.go, plugin/client/auth_client.go, plugin/client/blobstore.go, plugin/client/code_quality.go, plugin/client/gitbranch.go, plugin/client/gitcommit.go, plugin/client/gitcommitcomment.go, plugin/client/gitcommitstatus.go, plugin/client/gitcontent.go, plugin/client/gitfiletree.go, plugin/client/gitpullrequest.go, plugin/client/gitrepository.go, plugin/client/gitrepotag.go, plugin/client/plugin_client.go, plugin/client/project.go, plugin/client/repository.go, plugin/client/testcase.go, plugin/client/testcaseexecution.go, plugin/client/testmodule.go, plugin/client/testplan.go, plugin/client/tool_service.go
https://github.com/katanomi/pkg/pull/237 这个 pr 给 plugin client 增加了 meta、secret 字段，但是传递 meta、secret 的逻辑比较绕。
pr 对这部分做了简化，meta、secret 最终是给 plugin client 使用的，在内部处理就好，不需要传给后续的 client 了。
=> remove ambiguous plugin field

apis/meta/v1alpha1/labels_annotations.go, apis/selection/v1alpha1/cluster_filter.go, apis/selection/v1alpha1/cluster_filter_test.go, apis/selection/v1alpha1/get_clusters.go, apis/selection/v1alpha1/get_clusters_test.go, hack/boilerplate.go.txt, multicluster/clusterregistry_client.go
Allows the namespace to be empty, indicating the namespace where the current resource is located.
- https://github.com/katanomi/spec/pull/209
=> fix: validate for clusterfilter

apis/applications/v1alpha1/deploy_application_status.go, apis/meta/v1alpha1/condition.go, apis/meta/v1alpha1/condition_test.go
=> fix: Make name in NamedDeployApplicationResult omitempty

client/rbac_filter.go, client/rbac_filter_test.go, multicluster/filter.go, multicluster/filter_test.go
=> chore: support cross cluster authentication

client/context.go, client/context_test.go, client/manager.go, client/rbac_filter.go, plugin/storage/route/archive/v1alpha1/archive.go, plugin/storage/route/core/v1alpha1/auth.go, plugin/storage/route/filestore/v1alpha1/filemeta.go, plugin/storage/route/filestore/v1alpha1/fileobject.go, plugin/storage/route/route.go, sharedmain/app.go
support inject rest config of app into context for get rest config of pod when construct plugin client 
```release-note
NONE
```
=> add support for app config

apis/artifacts/v1alpha1/uri.go, go.mod, go.sum, hash/hash.go, hash/hash_test.go, registry/manifests.go, registry/manifests_test.go
=> manifest operation

apis/meta/v1alpha1/labels_annotations.go, apis/meta/v1alpha1/project_types.go, plugin/client/interface.go
There are different links for different uses of tools, add dependencyAddress field in the project, and support dependent repository address.
update in spec is here:https://github.com/katanomi/spec/pull/226/files 
=> feat: add extededAddresses field to project struct.

multicluster/context.go
WithIgnoreForbidden will overwrite ClusterNames value in context
```release-note
bug fix: WithIgnoreForbidden will overwrite ClusterNames value in context
```
=> fix error of IgnoreForbidden overwrite ClusterNames in context

plugin/client/plugin_client.go, plugin/storage/client/client.go
fix response message data race
=> fix response message data race

hash/hash.go, hash/hash_test.go
fix error when hash file is a symlink
=> fix symlink error

regex/replace.go, regex/replace_test.go, regex/testdata/replaces_validation.InvalidData.original.yaml, regex/testdata/replaces_validation.Valid.original.yaml
- https://github.com/katanomi/spec/pull/233
=> feat: support toLower and toUpper in regex replace

artifacts/tags.go, artifacts/tags_test.go
=> feat: Add find matched tag functionality

apis/archive/v1alpha1/field.go, apis/meta/v1alpha1/cursor.go
=> chore: add extData field to timeCursor struct

client/impersonate_filter.go, client/impersonate_filter_test.go, user/filter_test.go, user/filters.go
fix bugs that user could use invalid token (unauthorized) to get user owned resource
If user provide a valid jwt token but unauthorized, the UserOwnedResourcePermissionFilter cannot reject it with 401.
So, change SubjectAccessReview to SelfSubjectAccessReview to deal with unauthorized token.
```release-note
bug fixes:  fix bugs that user could use invalid token to get user owned resource
```
=>  fix bugs that user could use invalid token to get user owned resource

controllers/builderoptions.go, controllers/builderoptions_test.go, controllers/controllerbuilderoptions.go, controllers/controllerbuilderoptions_test.go, controllers/controllers_suite_test.go
add controller builder options and funcs
=> feat: add controller builder options and funcs

client/defaults.go, client/defaults_test.go
* added HttpClientOptionFunc for NewHTTPClient method
clean imports
* added testcase for NewHTTPClient
* impl HttpClientOption InsecureSkipVerifyOption
* added notes for InsecureSkipVerifyOption
=> added HttpClientOptionFunc for NewHTTPClient method (#456)

client/rbac_filter.go, client/rbac_filter_test.go, multicluster/types.go, resource/doc.go, resource/resources.go, resource/resources_test.go
1. add resource sum.
2. check resource permissions
=> feat: add support resource sum.

apis/meta/v1alpha1/buildmetadata_funcs.go
fix: check pr properties nil.
when plugin response not set properties, there will panic.
=> fix: check pr properties nil.

apis/meta/v1alpha1/labels_annotations.go, config/feature_flags.go
=> add proxy feature gate

config/feature_flags.go, config/feature_value.go, config/feature_value_test.go
=> add templaterender timeout

registry/helper.go
Add the ignore of hostname type certificate in registry
=> fix: add hostname tls ingnore for swr.

config/feature_flags.go, controllers/retry.go, controllers/retry_test.go, controllers/testdata/pod.yaml, tekton/apply.go, tekton/apply_test.go
Add config key for policyrun rentation time
=> Replacements will generate string array and object replacements

secret/mutate.go, secret/mutate_test.go
=> add secret mutator

apis/validation/name_validation.go, apis/validation/name_validation_test.go
=> fix: webhook for resource name

parallel/task.go, parallel/task_test.go
=> fix: refactor SetMaxConcurrent method in ParallelTasks.

apis/meta/v1alpha1/condition.go, apis/meta/v1alpha1/constant.go, controllers/manager.go, controllers/manager_test.go, sharedmain/app.go
1. some event message come from error of tools, we cannot decide the content length , it will causes etcd db size increasing
2. shorten condition message length
```release-note
Fix: fix long event message content breaks etcd
```
=> shorten message length in event message

config/config_suite_test.go, config/feature_flags.go, config/rest_filter.go, config/rest_filter_test.go, errors/errorhandling.go, plugin/plugin.go, plugin/route/healthz.go, plugin/route/helper.go, plugin/route/route.go, plugin/route/system.go, sharedmain/app.go
In order to disable access in production environments, a new filter was added to disable access when the configuration is set to any non true value. When changing the value the filter will pass and go tool pprof can be used directly
=> feat: Add pprof.enabled configuration flag for /debug/pprof APIs (#505)

plugin/route/system.go
Set API content types to JSON avoid 406 Not Acceptable.
=> chore: set json content type for system api

testing/fake/filter.go, testing/fake/filter_test.go, testing/framework/cluster/service.go
=> clone request to ready twice

plugin/client/base/options.go, plugin/client/base/options_test.go, plugin/client/v2/repository.go
=> fix: plugin sdk passes sorting parameters

.build/downstream-test.yaml, apis/meta/v1alpha1/condition.go, apis/meta/v1alpha1/constant.go, controllers/manager.go, controllers/manager_test.go, sharedmain/app.go
cherry-pick https://github.com/katanomi/pkg/pull/501
1. some event message come from error of tools, we cannot decide the content length , it will causes etcd db size increasing
2. shorten condition message length
```release-note
Fix: fix long event message content breaks etcd
```
=> Cherry pick/fix/shorten message in event

plugin/types/pull_request.go, plugin/types/webhook.go
=> chore: split plugin interfaces

multicluster/clusterregistry_client.go, multicluster/clusterregistry_client_test.go, multicluster/proxy.go, multicluster/proxy_test.go, sharedmain/app.go
=> support cluster proxy

apis/meta/v1alpha1/labels_annotations.go, webhook/admission/transform.go, webhook/admission/transform_test.go
=> add update time webhook

testing/framework/case_builder.go, testing/label.go, testing/label_test.go
ginkgo 生成的 junit 报告中的 case 名称包含了用例的描述，所以要定义个特殊的格式来识别唯一名称。
现在代码中定义的格式是 `{case:the-real-unique-case-name}`，如 `{case:GetProject}`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="9" disabled="0" errors="0" failures="0" time="0.000668">
<testsuite name="integrations-e2e" package="/Users/xx/code/katanomi/integrations/test/e2e" tests="9" disabled="0" skipped="0" errors="0" failures="0" time="0.000668" timestamp="2024-02-28T19:21:23">
<testcase name="[SynchronizedBeforeSuite]" classname="integrations-e2e" status="passed" time="0"></testcase>
<testcase name="[It] [P1][ClusterIntegrationSyncPeriod] when Manual-Private-two-ns should change status from ready to not ready [{case:GetProject}, controller, integration]" classname="integrations-e2e" status="passed" time="0"></testcase> …
```
=> feat: add helper function to generate unique case name

parallel/task_test.go, testing/convert.go, testing/convert_test.go, testing/testing_suite_test.go
=> fix: unit test not stable

apis/meta/v1alpha1/buildmetadata_funcs.go
Some objects are missing already existing attributes and relying exclusively on a properties structure
=> fix: Correcting BuildMeta generation methods from Git Objects

testing/expect.go, testing/expect_test.go, testing/framework/cluster/kubernetes.go, testing/framework/cluster/kubernetes_test.go
add ExpectKubeResExistsAndEqualTo func to assert resources in cluster
it expects kubernetes resource exists and expects the resource is equal to `expectObject`
```release-note
NONE
```
=> add ExpectKubeResExistsAndEqualTo func to assert resources in cluster

testing/framework/cluster/kubernetes.go, testing/framework/cluster/kubernetes_test.go, testing/framework/cluster/testdata/LoadKubeResources.configmap-withns.yaml, testing/framework/cluster/testdata/LoadKubeResources.configmap.yaml, testing/framework/cluster/testdata/LoadKubeResources.invalid.yaml
1. when we load kube resource in TestContext, we usually want to creat object namespace according TestContext, but we cannot assume the namespace in resource file
```release-note
NONE
```
=> Add LoadKubeResources in TestContext

maps/maps_suite_test.go, maps/select.go, maps/select_test.go
Add func for selecting and mutating map element
=> Add func for selecting and mutating map element

testing/framework/framework.go
Make logger accessible inside context for easier consumption by test cases and other functions
=> test: Add logger to framework's context

logging/config.go, logging/config_test.go, logging/klog.go, logging/klog_test.go, logging/suite_test.go, logging/testdata/config.yaml, sharedmain/app.go
=> feat: support update klog log level dynamically based on configmap

apis/meta/v1alpha1/gitbase_types.go, apis/meta/v1alpha1/gitbase_types_test.go
Lots of places might depend on printing the project/repository format for logging or just for convenience. The ProjectID() implementation was changed to use the String() method as to make it uniform
=> feat: Add String() method to meta/v1alpha1/GitRepo structure

testing/assertions/diff.go, testing/assertions/diff_test.go
In some test cases the data inside TypeMeta and RawExtension are not compulsory and can be ignored. Adding this variables here are for helping developers quickly reuse this cmp.Options and save time
=> feat: Add IgnoreTypeMeta and IgnoreRawExtension cmp.Options

sonar-project.properties, testing/framework/cluster/builder.go, testing/framework/cluster/condition.go, testing/framework/cluster/report.go, testing/report.go, testing/scheme.go
Add the ability to specify ObjectLists that will be reported after a failed test case. This uses the existing ReportObjectsLists functionality to print the object lists.
To use this, call WithObjectListReport on a TestCaseBuilder with the desired ObjectList instances. Then these will be reported after any failing test case.
This can help debug issues by printing extra object state.
=> feat: add object list reporting to test cases

testing/framework/cluster/report.go
ReportObjectsLists now accepts a namespace option to filter results to the test context namespace.
This avoids noise from unrelated namespaces in test reports.
=> feat: add namespace filtering for ReportObjectsLists

testing/framework/conformance/interface.go, testing/framework/conformance/layout.go, testing/framework/conformance/testpoint.go
This adds a new LazyFeatureCaseBuilder type that allows lazily loading feature cases only when needed. This avoids creating all feature cases upfront when defining the module.
A new GetFeatureCase method on moduleCase allows retrieving a lazy feature case builder by name.
The FeatureCaseBuilder interface is introduced with Labels() to get labels on feature cases. lazyFeatureCaseBuilder implements this to look up the real feature case labels only when Labels() is called.
additionalAssertions on testPoint now accepts FeatureCaseBuilder instead of *featureCase directly.
before the change:
after:
=> feat: add lazy loading for feature cases

testing/assertions/diff.go, testing/assertions/nil-empty.go, testing/assertions/nil-empty_test.go
Provide convinient method to compare empty values and pointers to empty values
=> feat: Add BeNilOrEmpty assertion in testing/assertion

tekton/taskrun_sort_completion.go, tekton/taskrun_test.go
TaskRun sort by completed time but if time is same then the sort is not stable.
So if time is same then compare the namespace and name.
=> Make the taskRun sort stable

config/feature_flags.go
chore: add global credentials namespace key
from: https://github.com/katanomi/core/blob/cfdfb89db77e92a5d985ac463c322657e80b6456/pkg/integrations/integrationaddress_dependencies.go#L49-L51
=> chore: add global credentials namespace key

.build/build.yaml
=> chore: upgrade builder-go to latest version
